queue_rules:
  - name: Auto Merge
    commit_message_template: "fix: patch"
    draft_bot_account: draftify[bot]
    update_bot_account: updatify[bot]
    autoqueue: true
pull_request_rules:
  - name: Make sure PR are almost up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      update:
  - name: Make sure PR are update before merging with rebase
    description: This automatically rebases PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step us switch to merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      rebase:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
    actions:
      merge:
  - name: Automatic merge during office hours + hotfix support
    description: Merge when PR passes all branch protection during office hours,
      except for hotfix
    conditions:
      - or:
          - schedule = Mon-Fri 09:00-17:00[America/Los_Angeles]
          - label = hotfix
    actions:
      merge:
  - name: Label Mergify Stacks PRs
    description: Pull requests that are part of a Mergify stack should be labeled as such
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
    actions:
      label:
        toggle:
          - stack
  - name: Label first PR of Mergify Stacks PRs
    description: The first PR of a Mergify stack should be labeled as such
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
      - -base ~= ^mergify_cli/
    actions:
      label:
        toggle:
          - top of the stack
